image:
  file: .gitpod.Dockerfile
tasks:
  - before:
      echo "Preparing...."
    init: |
      cabal update
      stack build
    command: |
      stack test

vscode:
  extensions:
    - haskell.haskell