image:
  file: .gitpod.Dockerfile
tasks:
  - before: |
      echo "source ~/.ghcup/env" >> ~/.bashrc
      source ~/.ghcup/env
  - init: |
      cabal update
      stack build
  - command: |
      stack test

vscode:
  extensions:
    - haskell.haskell