image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      echo "source ~/.ghcup/env" >> ~/.bashrc
      source ~/.ghcup/env
      cabal update
      stack build

    command: |
      stack test

vscode:
  extensions:
    - haskell.haskell